version: 2
jobs:
  build:
  #  ...
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command:
            - ssh $SSH_USER@$SSH_HOST 'cd /var/www/html/ && echo "GIT PULL" > index.html'
  deploy_production:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: ssh $SSH_USER@$SSH_HOST
      - run:
          name: GO TO FOLDER
          command: cd /var/www/html
      - run:
          name: GIT PULL
          command: echo "GIT PULL PRODUCTION" > index.html
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: master